import React from "react";
import { View, Text, StyleSheet, ScrollView, ActivityIndicator, TouchableOpacity, Alert } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useHumanOverrideDetail } from "../../../src/hooks/useHumanOverrideDetail";
import { useHumanOverrideActions } from "../../../src/hooks/useHumanOverrideActions";

export default function OverrideDecisionScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { request, options, loading } = useHumanOverrideDetail(id);
  const { submitDecision } = useHumanOverrideActions();

  if (loading || !request) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#b91c1c" />
      </View>
    );
  }

  const handleSelectOption = async (optionId: string) => {
    await submitDecision(request.id, optionId, "SYSTEM_ADMIN");
    Alert.alert("Decision Recorded", "System will resume on selected branch.", [
      { text: "OK", onPress: () => router.push(`/override/resume?id=${request.id}`) }
    ]);
  };

  return (
    <ScrollView style={styles.container}>
      <Text style={styles.header}>Arbitration Interface</Text>
      <Text style={styles.subtitle}>Frozen State: {id}</Text>
      
      <View style={styles.dangerBox}>
        <Text style={styles.dangerText}>HALT REASON: {request.haltReason}</Text>
      </View>

      <Text style={styles.sectionTitle}>Aggregated Conflict Traces</Text>
      
      {request.frozenState.aPlusRejection && (
        <View style={styles.layerBox}>
          <Text style={styles.layerTitle}>A+ (Execution Guard) Block</Text>
          <Text style={styles.layerData}>{request.frozenState.aPlusRejection}</Text>
        </View>
      )}

      {request.frozenState.cPlusPlusConflicts && request.frozenState.cPlusPlusConflicts.length > 0 && (
        <View style={styles.layerBox}>
          <Text style={styles.layerTitle}>C++ (Truth Tension) Warning</Text>
          {request.frozenState.cPlusPlusConflicts.map((c, i) => <Text key={i} style={styles.layerData}>• {c}</Text>)}
        </View>
      )}

      <Text style={styles.sectionTitle}>Human Resolution Options</Text>
      
      {options.map((option) => (
        <TouchableOpacity 
          key={option.id} 
          style={styles.optionCard}
          onPress={() => handleSelectOption(option.id)}
        >
          <View style={styles.optionHeader}>
            <Text style={styles.optionSource}>Generated by: World {option.sourceLayer}</Text>
          </View>
          <Text style={styles.optionLabel}>{option.label}</Text>
          <Text style={styles.optionTrace}>{option.consequenceTrace}</Text>
        </TouchableOpacity>
      ))}

    </ScrollView>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  container: { flex: 1, padding: 16, backgroundColor: "#fef2f2" },
  header: { fontSize: 26, fontWeight: "bold", color: "#7f1d1d" },
  subtitle: { fontSize: 13, color: "#991b1b", marginBottom: 20, fontFamily: "monospace" },
  
  dangerBox: { backgroundColor: "#fee2e2", padding: 16, borderRadius: 8, borderWidth: 1, borderColor: "#ef4444", marginBottom: 24 },
  dangerText: { fontSize: 16, color: "#b91c1c", fontWeight: "bold" },

  sectionTitle: { fontSize: 16, fontWeight: "bold", color: "#991b1b", marginBottom: 12, borderBottomWidth: 1, borderBottomColor: "#fecaca", paddingBottom: 8 },
  
  layerBox: { backgroundColor: "#fff", padding: 12, borderRadius: 8, marginBottom: 12, borderWidth: 1, borderColor: "#fca5a5" },
  layerTitle: { fontSize: 13, fontWeight: "bold", color: "#b91c1c", marginBottom: 6 },
  layerData: { fontSize: 13, color: "#7f1d1d", fontFamily: "monospace" },

  optionCard: { backgroundColor: "#fff", padding: 16, borderRadius: 8, marginBottom: 12, borderWidth: 2, borderColor: "#f87171", elevation: 2 },
  optionHeader: { marginBottom: 8 },
  optionSource: { fontSize: 11, fontWeight: "bold", color: "#dc2626" },
  optionLabel: { fontSize: 16, fontWeight: "bold", color: "#7f1d1d", marginBottom: 8 },
  optionTrace: { fontSize: 13, color: "#991b1b", fontStyle: "italic" }
});
